# 数据库配置
spring:
  # mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: root
    password: ssx14233
    # redis数据库配置
  redis:
    host: 127.0.0.1 # redis的主机ip
    port: 6379 # 端口

#tomcat
server:
  port: 8080 # 设置端口号
  servlet:
    context-path: / #设置上下文路径

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打开SQL日志文件输出在控制台
  global-config:
    db-config:
      id-type: auto # 全局的id生成策略
  mapper-locations: classpath:mapper/*Mapper.xml # 加载xml映射文件
  type-aliases-package: com.tionkior.pojo # 设置别名

# 日志信息保存
logging:
  file:
    name: log.txt
 